default:
  tags:
    - nix

variables:
  NIX_BUILD_FLAGS: "--no-update-lock-file --print-build-logs --show-trace"

before_script:
  - git config --global url."https://gitlab-ci-token:${CI_JOB_TOKEN}@drf-gitlab.cea.fr".insteadOf "ssh://git@drf-gitlab.cea.fr"

pdf:
  stage: deploy
  script:
    - nix develop $NIX_BUILD_FLAGS -i -c typst compile main.typ main.pdf
  artifacts:
    name: "Convention de nommage EPICS pour TITAN.pdf"
    paths:
      - main.pdf
  needs: []
  dependencies: []
